package com.techelevator.company;

public class Company {

	private String name;
	private int numberOfEmployees;
	private double revenue;
	private double expenses;

	// Method

	/*
	 * Company Size is if less than or equal to 50 "Small", between 51 and 250 is
	 * "medium and 250 or larger is "large".
	 */

	public String getCompanySize() {
		if (this.numberOfEmployees <= 50) {
			return "small";

		} else if (this.numberOfEmployees >= 51 && this.numberOfEmployees <= 250) {
			return "medium";
		} else {
			return "large";
		}

	}

	// Profit is the difference between revenue and expenses
	public double getProfit() {
		return (this.revenue - this.expenses);
	}

	// The company class is using the default constructor, so no need to add any
	// items.
	public Company() {

	}

	// Getters and Setters are generated by Eclipse.
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNumberOfEmployees() {
		return numberOfEmployees;
	}

	public void setNumberOfEmployees(int numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees;
	}

	public double getRevenue() {
		return revenue;
	}

	public void setRevenue(double revenue) {
		this.revenue = revenue;
	}

	public double getExpenses() {
		return expenses;
	}

	public void setExpenses(double expenses) {
		this.expenses = expenses;
	}
}